import { TransitionTopic } from './types';

export const ALL_TRANSITION_TOPICS: TransitionTopic[] = [
  // Class 7-10 Boards
  {
    key: 'pythagoras',
    label: 'Pythagorean Theorem & Trig Ratios',
    icon: 'square_foot',
    grade: 'Class 7-10',
    standardGroup: 'Class 9-10',
    category: 'Trigonometry',
    shortDesc: 'Right triangle side squares proof and sin, cos, tan angular ratios.',
    badge: 'Core Theorem',
  },
  {
    key: 'unit_circle',
    label: 'Unit Circle & Sine / Cosine Wave Morph',
    icon: 'rotate_right',
    grade: 'Class 10-12',
    standardGroup: 'Class 11-12 & Olympiad',
    category: 'Trigonometry',
    shortDesc: '360° rotating point P(cos θ, sin θ) with real-time wave graph and ASTC quadrants.',
    badge: 'Senior Secondary',
  },
  {
    key: 'quadratic',
    label: 'Quadratic Equations & Parabola Morph',
    icon: 'ssid_chart',
    grade: 'Class 9-11',
    standardGroup: 'Class 9-10',
    category: 'Algebra',
    shortDesc: 'ax² + bx + c = 0 curvature, vertex (h,k), discriminant D nature of roots.',
    badge: 'High Frequency',
  },
  {
    key: 'algebraic',
    label: 'Algebraic Area Box & Identities',
    icon: 'view_quilt',
    grade: 'Class 7-9',
    standardGroup: 'Class 5-8',
    category: 'Algebra',
    shortDesc: 'Visual 2D rectangle partition proofs for (a+b)², (a-b)², and a²-b².',
    badge: 'Foundations',
  },
  {
    key: 'linear_systems',
    label: 'Linear Equations & Intersection Systems',
    icon: 'stacked_line_chart',
    grade: 'Class 9-10',
    standardGroup: 'Class 9-10',
    category: 'Algebra',
    shortDesc: 'Two lines intersection point, parallel condition (no solution), coincident lines.',
    badge: 'NCERT Ch 3',
  },
  {
    key: 'progressions',
    label: 'Arithmetic Progression (AP) Staircase',
    icon: 'stairs',
    grade: 'Class 10-11',
    standardGroup: 'Class 9-10',
    category: 'Algebra',
    shortDesc: 'Stepped sequence aₙ = a + (n-1)d and accumulated sum Sₙ Gauss pairing.',
    badge: 'Board Regular',
  },
  {
    key: 'geom_progression',
    label: 'Geometric Progression (GP) & Infinite Series',
    icon: 'trending_up',
    grade: 'Class 10-12',
    standardGroup: 'Class 11-12 & Olympiad',
    category: 'Algebra',
    shortDesc: 'Exponential scaling bar steps a, ar, ar² and infinite convergent sum S_∞.',
    badge: 'Olympiad & JEE',
  },
  {
    key: 'circle',
    label: 'Circle Geometry, Arc Length & Sector Area',
    icon: 'pie_chart',
    grade: 'Class 6-10',
    standardGroup: 'Class 9-10',
    category: 'Geometry',
    shortDesc: 'Dynamic sector wedge (θ/360)πr², boundary arc (θ/360)2πr, and unrolled perimeter.',
    badge: 'Mensuration',
  },
  {
    key: 'similar_triangles',
    label: 'Similar Triangles & Thales Theorem (BPT)',
    icon: 'change_history',
    grade: 'Class 9-10',
    standardGroup: 'Class 9-10',
    category: 'Geometry',
    shortDesc: 'Triangle ABC with parallel line DE || BC, proportional ratios AD/DB = AE/EC.',
    badge: 'Proof Theorem',
  },
  {
    key: 'coordinate_geom',
    label: 'Coordinate Distance, Midpoint & Section Formula',
    icon: 'location_searching',
    grade: 'Class 9-11',
    standardGroup: 'Class 9-10',
    category: 'Geometry',
    shortDesc: 'Cartesian distance d = √((Δx)² + (Δy)²) and internal division point in ratio m:n.',
    badge: 'Analytical',
  },
  {
    key: 'lines_angles',
    label: 'Parallel Lines, Transversals & Angle Pairs',
    icon: 'linear_scale',
    grade: 'Class 6-8',
    standardGroup: 'Class 5-8',
    category: 'Geometry',
    shortDesc: 'Interactive transversal line with alternate interior, corresponding, and co-interior angles.',
    badge: 'Middle School',
  },
  {
    key: 'mensuration',
    label: '3D Solid Surface Nets Unfolding',
    icon: 'view_in_ar',
    grade: 'Class 7-10',
    standardGroup: 'Class 9-10',
    category: 'Mensuration',
    shortDesc: 'Unfold cylinder, cone, cube, and sphere 3D solids into flat 2D nets for CSA and TSA.',
    badge: '3D Spatial',
  },
  {
    key: 'fractions',
    label: 'Fraction, Decimal & Percentage Transition',
    icon: 'percent',
    grade: 'Class 5-7',
    standardGroup: 'Class 5-8',
    category: 'Arithmetic & Numbers',
    shortDesc: 'Dynamic pie slices and bar fills converting between fraction, decimal, and percentage.',
    badge: 'Foundations',
  },
  {
    key: 'statistics',
    label: 'Mean, Median, Mode & Bell Balance',
    icon: 'bar_chart',
    grade: 'Class 6-10',
    standardGroup: 'Class 5-8',
    category: 'Statistics & Probability',
    shortDesc: 'Interactive frequency fulcrum (Mean), sorted midpoint (Median), peak mode, and empirical rule.',
    badge: 'Data Science',
  },
  {
    key: 'probability',
    label: 'Probability & Binomial Distribution Simulator',
    icon: 'casino',
    grade: 'Class 9-12',
    standardGroup: 'Class 11-12 & Olympiad',
    category: 'Statistics & Probability',
    shortDesc: 'Coin & dice trials, Pascal binomial coefficient bars, and expected value E(X).',
    badge: 'Probability',
  },
  {
    key: 'calculus',
    label: 'Secant to Tangent Derivative Transition',
    icon: 'show_chart',
    grade: 'Class 11-12 & Olympiad',
    standardGroup: 'Class 11-12 & Olympiad',
    category: 'Calculus',
    shortDesc: 'Watch the secant line morph into an instantaneous tangent line as Δx → 0 (derivative slope).',
    badge: 'Advanced Calculus',
  },
];
